<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pages')->delete();
        
        \DB::table('pages')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => NULL,
                'template' => 'home',
                'article_type' => NULL,
                'slug' => 'ana-sehife',
                'ordering' => 1,
                'status' => 1,
                'visible_in_sidebar' => 1,
                'child_visible_in_sidebar' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-09-09 08:34:03',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/ana-sehife',
            ),
            1 => 
            array (
                'id' => 181,
                'parent_id' => 1,
                'template' => 'umumi-sorgular',
                'article_type' => NULL,
                'slug' => 'sorgular',
                'ordering' => 9,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2022-04-28 21:02:05',
                'updated_at' => '2022-11-22 09:01:47',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/ana-sehife/sorgular',
            ),
            2 => 
            array (
                'id' => 379,
                'parent_id' => NULL,
                'template' => 'redirect',
                'article_type' => NULL,
                'slug' => 'bizim-liman',
                'ordering' => 11,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 1,
                'created_at' => '2023-03-26 04:57:12',
                'updated_at' => '2023-03-26 04:57:15',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/bizim-liman',
            ),
            3 => 
            array (
                'id' => 380,
                'parent_id' => 379,
                'template' => 'tarix',
                'article_type' => NULL,
                'slug' => 'tarix',
                'ordering' => 1,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-26 04:57:38',
                'updated_at' => '2023-03-26 04:57:40',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/bizim-liman/tarix',
            ),
            4 => 
            array (
                'id' => 381,
                'parent_id' => 379,
                'template' => 'limanin-inkisafi-yol-xeritesi',
                'article_type' => NULL,
                'slug' => 'limanin-inkisafi-yol-xeritesi',
                'ordering' => 2,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-26 05:08:38',
                'updated_at' => '2023-03-26 05:12:45',
                'image' => 'JMsyzlUCcMjTretDBcuURfM6zkh4t8jPVeKCgvHx.png',
                'icon' => NULL,
                'url' => 'page/bizim-liman/limanin-inkisafi-yol-xeritesi',
            ),
            5 => 
            array (
                'id' => 382,
                'parent_id' => 379,
                'template' => 'mission',
                'article_type' => NULL,
                'slug' => 'missiya-baxis-ve-deyerler',
                'ordering' => 3,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-26 05:45:22',
                'updated_at' => '2023-03-26 05:49:13',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/bizim-liman/missiya-baxis-ve-deyerler',
            ),
            6 => 
            array (
                'id' => 383,
                'parent_id' => 379,
                'template' => 'idare-heyeti',
                'article_type' => NULL,
                'slug' => 'idare-heyeti',
                'ordering' => 4,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-27 01:02:30',
                'updated_at' => '2023-03-27 01:02:31',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/bizim-liman/idare-heyeti',
            ),
            7 => 
            array (
                'id' => 384,
                'parent_id' => 383,
                'template' => 'idare-heyeti-inner',
                'article_type' => NULL,
                'slug' => 'mansur-mammadov',
                'ordering' => 1,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-27 01:06:44',
                'updated_at' => '2023-03-27 01:07:11',
                'image' => '7fzA5cjVCJifzZmR5FGdAW2Wr4T3JSHJHJPSjnWH.png',
                'icon' => NULL,
                'url' => 'page/bizim-liman/idare-heyeti/mansur-mammadov',
            ),
            8 => 
            array (
                'id' => 385,
                'parent_id' => 383,
                'template' => 'idare-heyeti-inner',
                'article_type' => NULL,
                'slug' => 'jalal-gaytaranov',
                'ordering' => 2,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-27 01:11:26',
                'updated_at' => '2023-03-27 01:11:40',
                'image' => 'l17im0dPjgixgxS81qWtQeCiVI6GYvXAES6qlL7D.png',
                'icon' => NULL,
                'url' => 'page/bizim-liman/idare-heyeti/jalal-gaytaranov',
            ),
            9 => 
            array (
                'id' => 387,
                'parent_id' => 383,
                'template' => 'idare-heyeti-inner',
                'article_type' => NULL,
                'slug' => 'jalal-gaytaranov1',
                'ordering' => 3,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-27 01:12:44',
                'updated_at' => '2023-03-27 01:12:52',
                'image' => 'bzjJe0U1Dn0OG3DuO1fBuMGEZD7csEWEImupwZXY.png',
                'icon' => NULL,
                'url' => 'page/bizim-liman/idare-heyeti/jalal-gaytaranov1',
            ),
            10 => 
            array (
                'id' => 388,
                'parent_id' => 383,
                'template' => 'idare-heyeti-inner',
                'article_type' => NULL,
                'slug' => 'jalal-gaytaranov2',
                'ordering' => 4,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-27 01:13:07',
                'updated_at' => '2023-03-27 01:13:14',
                'image' => 'XIEPQm2TJl8EhAhKDnEFVX5au8MjALIiZE686HBS.png',
                'icon' => NULL,
                'url' => 'page/bizim-liman/idare-heyeti/jalal-gaytaranov2',
            ),
            11 => 
            array (
                'id' => 389,
                'parent_id' => 383,
                'template' => 'idare-heyeti-inner',
                'article_type' => NULL,
                'slug' => 'jalal-gaytaranov3',
                'ordering' => 5,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-27 01:13:27',
                'updated_at' => '2023-03-27 01:13:35',
                'image' => '5rnHUkD40dz3KFoOaayiduXtxG8VQaJ5BvKZoSEB.png',
                'icon' => NULL,
                'url' => 'page/bizim-liman/idare-heyeti/jalal-gaytaranov3',
            ),
            12 => 
            array (
                'id' => 390,
                'parent_id' => 383,
                'template' => 'idare-heyeti-inner',
                'article_type' => NULL,
                'slug' => 'jalal-gaytaranov4',
                'ordering' => 6,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-27 01:13:50',
                'updated_at' => '2023-03-27 01:13:57',
                'image' => 'deDQS7fOFUrzNSan096KwfDO5b2YNe7sMSxVE3qW.png',
                'icon' => NULL,
                'url' => 'page/bizim-liman/idare-heyeti/jalal-gaytaranov4',
            ),
            13 => 
            array (
                'id' => 391,
                'parent_id' => 383,
                'template' => 'idare-heyeti-inner',
                'article_type' => NULL,
                'slug' => 'jalal-gaytaranov6',
                'ordering' => 7,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-27 01:14:19',
                'updated_at' => '2023-03-27 01:14:27',
                'image' => 'TugcWNkLG5pwbu2EWVuJ9LpIPSmjcHH4Z8yLEhhP.png',
                'icon' => NULL,
                'url' => 'page/bizim-liman/idare-heyeti/jalal-gaytaranov6',
            ),
            14 => 
            array (
                'id' => 392,
                'parent_id' => 379,
                'template' => 'illik-raport',
                'article_type' => NULL,
                'slug' => 'illik-raport',
                'ordering' => 5,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-27 01:40:02',
                'updated_at' => '2023-03-27 01:40:03',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/bizim-liman/illik-raport',
            ),
            15 => 
            array (
                'id' => 393,
                'parent_id' => NULL,
                'template' => 'redirect',
                'article_type' => NULL,
                'slug' => 'biznes',
                'ordering' => 12,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 1,
                'created_at' => '2023-03-27 01:54:50',
                'updated_at' => '2023-03-27 01:54:52',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/biznes',
            ),
            16 => 
            array (
                'id' => 394,
                'parent_id' => 393,
                'template' => 'content',
                'article_type' => NULL,
                'slug' => 'tarifler',
                'ordering' => 1,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-27 01:55:38',
                'updated_at' => '2023-03-27 01:56:12',
                'image' => 'Sxz9v1h0eoIque1DBwYB5ppGzuRikUwX4RhCKMzA.png',
                'icon' => NULL,
                'url' => 'page/biznes/tarifler',
            ),
            17 => 
            array (
                'id' => 395,
                'parent_id' => 393,
                'template' => 'mission',
                'article_type' => NULL,
                'slug' => 'multimodal-dasimalar',
                'ordering' => 2,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-27 02:00:09',
                'updated_at' => '2023-03-27 02:00:44',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/biznes/multimodal-dasimalar',
            ),
            18 => 
            array (
                'id' => 396,
                'parent_id' => NULL,
                'template' => 'redirect',
                'article_type' => NULL,
                'slug' => 'etraf-muhit',
                'ordering' => 13,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 1,
                'created_at' => '2023-03-27 02:02:53',
                'updated_at' => '2023-03-27 02:02:55',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/etraf-muhit',
            ),
            19 => 
            array (
                'id' => 397,
                'parent_id' => 396,
                'template' => 'sertifikatlar',
                'article_type' => NULL,
                'slug' => 'sertifikatlar',
                'ordering' => 1,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-27 02:05:09',
                'updated_at' => '2023-03-27 02:05:11',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/etraf-muhit/sertifikatlar',
            ),
            20 => 
            array (
                'id' => 398,
                'parent_id' => NULL,
                'template' => 'redirect',
                'article_type' => NULL,
                'slug' => 'insan-kapitali',
                'ordering' => 14,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 1,
                'created_at' => '2023-03-27 02:15:11',
                'updated_at' => '2023-03-27 02:15:13',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/insan-kapitali',
            ),
            21 => 
            array (
                'id' => 399,
                'parent_id' => 398,
                'template' => 'content',
                'article_type' => NULL,
                'slug' => 'insan-resurslari-siyasetimiz',
                'ordering' => 1,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-27 02:15:30',
                'updated_at' => '2023-03-27 02:15:50',
                'image' => 'qDuUGjcrS7dvxKnZsx5gFDGCtcJndQ6gBgfYI6IS.png',
                'icon' => NULL,
                'url' => 'page/insan-kapitali/insan-resurslari-siyasetimiz',
            ),
            22 => 
            array (
                'id' => 400,
                'parent_id' => 398,
                'template' => 'tecrube-proqrami',
                'article_type' => NULL,
                'slug' => 'tecrube-proqrami',
                'ordering' => 2,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-27 16:19:50',
                'updated_at' => '2023-03-27 16:19:52',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/insan-kapitali/tecrube-proqrami',
            ),
            23 => 
            array (
                'id' => 401,
                'parent_id' => NULL,
                'template' => 'redirect',
                'article_type' => NULL,
                'slug' => 'media-ve-xeberler',
                'ordering' => 15,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 1,
                'created_at' => '2023-03-30 13:15:31',
                'updated_at' => '2023-03-30 13:15:33',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/media-ve-xeberler',
            ),
            24 => 
            array (
                'id' => 402,
                'parent_id' => 401,
                'template' => 'article',
                'article_type' => 'news',
                'slug' => 'xeberler',
                'ordering' => 1,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-30 13:18:28',
                'updated_at' => '2023-03-30 13:18:34',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/media-ve-xeberler/xeberler',
            ),
            25 => 
            array (
                'id' => 403,
                'parent_id' => 401,
                'template' => 'article',
                'article_type' => 'brifing',
                'slug' => 'brifinqler',
                'ordering' => 2,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-30 15:40:45',
                'updated_at' => '2023-03-30 15:40:48',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/media-ve-xeberler/brifinqler',
            ),
            26 => 
            array (
                'id' => 404,
                'parent_id' => 401,
                'template' => 'arxiv',
                'article_type' => NULL,
                'slug' => 'xeber-arxivleri',
                'ordering' => 3,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-30 17:05:21',
                'updated_at' => '2023-03-30 17:05:23',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/media-ve-xeberler/xeber-arxivleri',
            ),
            27 => 
            array (
                'id' => 405,
                'parent_id' => 401,
                'template' => 'qalereya',
                'article_type' => NULL,
                'slug' => 'qalereya',
                'ordering' => 4,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-30 19:05:24',
                'updated_at' => '2023-03-30 19:05:26',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/media-ve-xeberler/qalereya',
            ),
            28 => 
            array (
                'id' => 406,
                'parent_id' => 401,
                'template' => 'article',
                'article_type' => 'video',
                'slug' => 'videolar',
                'ordering' => 5,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-30 19:35:24',
                'updated_at' => '2023-03-30 19:35:26',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/media-ve-xeberler/videolar',
            ),
            29 => 
            array (
                'id' => 407,
                'parent_id' => 401,
                'template' => 'contact',
                'article_type' => NULL,
                'slug' => 'elaqe-melumatlari',
                'ordering' => 6,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-30 20:00:29',
                'updated_at' => '2023-03-30 20:00:31',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/media-ve-xeberler/elaqe-melumatlari',
            ),
            30 => 
            array (
                'id' => 408,
                'parent_id' => 401,
                'template' => 'article',
                'article_type' => 'elanlar',
                'slug' => 'elanlar',
                'ordering' => 7,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-30 20:13:08',
                'updated_at' => '2023-03-30 20:13:11',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/media-ve-xeberler/elanlar',
            ),
            31 => 
            array (
                'id' => 409,
                'parent_id' => 401,
                'template' => 'sosial',
                'article_type' => NULL,
                'slug' => 'sosial-mesuliyyet',
                'ordering' => 8,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 0,
                'created_at' => '2023-03-30 20:23:19',
                'updated_at' => '2023-03-30 20:23:21',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/media-ve-xeberler/sosial-mesuliyyet',
            ),
            32 => 
            array (
                'id' => 410,
                'parent_id' => NULL,
                'template' => 'redirect',
                'article_type' => NULL,
                'slug' => 'beynelxalq-emekdasliq',
                'ordering' => 16,
                'status' => 1,
                'visible_in_sidebar' => NULL,
                'child_visible_in_sidebar' => 1,
                'created_at' => '2023-03-31 12:13:59',
                'updated_at' => '2023-03-31 12:14:10',
                'image' => NULL,
                'icon' => NULL,
                'url' => 'page/beynelxalq-emekdasliq',
            ),
        ));
        
        
    }
}