<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert(array (
            0 => 
            array (
                'id' => 2,
                'title' => 'permission',
                'description' => 'icazelere baxmaq',
                'model' => 'permission',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:37:40',
                'updated_at' => '2022-08-25 12:41:12',
            ),
            1 => 
            array (
                'id' => 5,
                'title' => 'role',
                'description' => 'role',
                'model' => 'role',
                'C' => 0,
                'R' => 1,
                'U' => 0,
                'D' => 0,
                'full' => 1,
                'created_at' => '2022-08-25 12:41:27',
                'updated_at' => '2022-08-25 13:33:03',
            ),
            2 => 
            array (
                'id' => 6,
                'title' => 'admin-users',
                'description' => 'admin-users',
                'model' => 'admin-users',
                'C' => 0,
                'R' => 1,
                'U' => 0,
                'D' => 0,
                'full' => 0,
                'created_at' => '2022-08-25 12:41:41',
                'updated_at' => '2022-08-25 13:32:29',
            ),
            3 => 
            array (
                'id' => 7,
                'title' => 'template',
                'description' => 'template',
                'model' => 'template',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:41:54',
                'updated_at' => '2022-08-25 12:41:54',
            ),
            4 => 
            array (
                'id' => 8,
                'title' => 'page',
                'description' => 'page',
                'model' => 'page',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:42:04',
                'updated_at' => '2022-08-25 13:25:01',
            ),
            5 => 
            array (
                'id' => 9,
                'title' => 'simple-item',
                'description' => 'simple-item',
                'model' => 'simple-item',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:42:17',
                'updated_at' => '2022-08-25 12:42:17',
            ),
            6 => 
            array (
                'id' => 10,
                'title' => 'menu',
                'description' => 'menu',
                'model' => 'menu',
                'C' => 0,
                'R' => 1,
                'U' => 0,
                'D' => 0,
                'full' => 1,
                'created_at' => '2022-08-25 12:42:28',
                'updated_at' => '2022-08-25 13:28:13',
            ),
            7 => 
            array (
                'id' => 11,
                'title' => 'article',
                'description' => 'article',
                'model' => 'article',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:42:39',
                'updated_at' => '2022-08-25 13:28:39',
            ),
            8 => 
            array (
                'id' => 12,
                'title' => 'position',
                'description' => 'position',
                'model' => 'position',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:42:50',
                'updated_at' => '2022-08-25 12:42:50',
            ),
            9 => 
            array (
                'id' => 13,
                'title' => 'profession',
                'description' => 'profession',
                'model' => 'profession',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:43:00',
                'updated_at' => '2022-08-25 12:43:00',
            ),
            10 => 
            array (
                'id' => 14,
                'title' => 'vacancy',
                'description' => 'vacancy',
                'model' => 'vacancy',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:43:12',
                'updated_at' => '2022-08-25 12:43:12',
            ),
            11 => 
            array (
                'id' => 15,
                'title' => 'struktur',
                'description' => 'struktur',
                'model' => 'struktur',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:43:23',
                'updated_at' => '2022-08-25 12:43:23',
            ),
            12 => 
            array (
                'id' => 18,
                'title' => 'video',
                'description' => 'video',
                'model' => 'video',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:43:58',
                'updated_at' => '2022-08-25 12:43:58',
            ),
            13 => 
            array (
                'id' => 19,
                'title' => 'struktur-item',
                'description' => 'struktur-item',
                'model' => 'struktur-item',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:44:14',
                'updated_at' => '2022-08-25 12:44:14',
            ),
            14 => 
            array (
                'id' => 20,
                'title' => 'project-category',
                'description' => 'project-category',
                'model' => 'project-category',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:44:28',
                'updated_at' => '2022-08-25 12:44:28',
            ),
            15 => 
            array (
                'id' => 21,
                'title' => 'survey-subject',
                'description' => 'survey-subject',
                'model' => 'survey-subject',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:44:40',
                'updated_at' => '2022-08-25 12:44:40',
            ),
            16 => 
            array (
                'id' => 22,
                'title' => 'survey-question',
                'description' => 'survey-question',
                'model' => 'survey-question',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:44:53',
                'updated_at' => '2022-08-25 12:44:53',
            ),
            17 => 
            array (
                'id' => 23,
                'title' => 'baku-for-tourist',
                'description' => 'baku-for-tourist',
                'model' => 'baku-for-tourist',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:45:07',
                'updated_at' => '2022-08-25 12:51:48',
            ),
            18 => 
            array (
                'id' => 24,
                'title' => 'baku-for-tourist-item',
                'description' => 'baku-for-tourist-item',
                'model' => 'baku-for-tourist-item',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:45:28',
                'updated_at' => '2022-08-25 12:45:28',
            ),
            19 => 
            array (
                'id' => 25,
                'title' => 'stations',
                'description' => 'stations',
                'model' => 'stations',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:45:44',
                'updated_at' => '2022-08-25 12:45:44',
            ),
            20 => 
            array (
                'id' => 26,
                'title' => 'search',
                'description' => 'search',
                'model' => 'search',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:45:55',
                'updated_at' => '2022-08-25 12:45:55',
            ),
            21 => 
            array (
                'id' => 27,
                'title' => 'contact',
                'description' => 'contact',
                'model' => 'contact',
                'C' => 1,
                'R' => 1,
                'U' => 1,
                'D' => 1,
                'full' => 1,
                'created_at' => '2022-08-25 12:46:11',
                'updated_at' => '2022-08-25 12:46:11',
            ),
            22 => 
            array (
                'id' => 29,
                'title' => 'menu-item',
                'description' => 'menu-item',
                'model' => 'menu-item',
                'C' => 0,
                'R' => 1,
                'U' => 0,
                'D' => 0,
                'full' => 1,
                'created_at' => '2022-08-25 12:47:15',
                'updated_at' => '2022-08-25 13:33:08',
            ),
            23 => 
            array (
                'id' => 30,
                'title' => 'menu-main',
                'description' => 'menu-main',
                'model' => 'menu-main',
                'C' => 0,
                'R' => 1,
                'U' => 0,
                'D' => 0,
                'full' => 1,
                'created_at' => '2022-08-25 12:47:31',
                'updated_at' => '2022-08-25 13:33:13',
            ),
            24 => 
            array (
                'id' => 31,
                'title' => 'simple-json',
                'description' => 'simple-json',
                'model' => 'simple-json',
                'C' => 0,
                'R' => 0,
                'U' => 0,
                'D' => 0,
                'full' => 1,
                'created_at' => '2022-08-25 12:52:27',
                'updated_at' => '2022-08-25 12:52:27',
            ),
            25 => 
            array (
                'id' => 32,
                'title' => 'article-types',
                'description' => 'article-types',
                'model' => 'article-types',
                'C' => 0,
                'R' => 0,
                'U' => 0,
                'D' => 0,
                'full' => 1,
                'created_at' => '2022-08-25 12:52:44',
                'updated_at' => '2022-08-25 12:52:44',
            ),
            26 => 
            array (
                'id' => 33,
                'title' => 'muraciet.admin',
                'description' => 'muraciet.admin',
                'model' => 'muraciet.admin',
                'C' => 0,
                'R' => 0,
                'U' => 0,
                'D' => 0,
                'full' => 1,
                'created_at' => '2022-08-25 12:53:37',
                'updated_at' => '2022-08-25 12:53:37',
            ),
            27 => 
            array (
                'id' => 34,
                'title' => 'settings-app',
                'description' => 'settings-app',
                'model' => 'settings-app',
                'C' => 0,
                'R' => 1,
                'U' => 0,
                'D' => 0,
                'full' => 1,
                'created_at' => '2022-08-25 12:56:15',
                'updated_at' => '2022-08-25 13:33:19',
            ),
            28 => 
            array (
                'id' => 35,
                'title' => 'translate',
                'description' => 'translate',
                'model' => 'translate',
                'C' => 0,
                'R' => 0,
                'U' => 0,
                'D' => 0,
                'full' => 1,
                'created_at' => '2022-08-25 13:12:18',
                'updated_at' => '2022-08-25 13:12:18',
            ),
        ));
        
        
    }
}